### ISSUE TITLE
GT-SALT/Multi-View-Seq2Seq, Please help with data format. 

### ISSUE THREAD

**Issue by Junpliu** [GT-SALT/Multi-View-Seq2Seq#9]
**Hi, 
  Thank you for great work. 
  When I run "train_multi_view.sh", I encountered this error,** 

epoch 001 | valid on 'valid' subset | loss 5.318 | nll_loss 3.057 | ppl 8.324 | wps 3513.7 | wpb 524.6 | bsz 20 | num_updates 24
here bpe NONE
here!
Test on val set:
Test on val set:
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/export/liujunpeng/code/Multi-View-Seq2Seq/fairseq_multi_view/fairseq_cli/train.py", line 435, in cli_main
    nprocs=args.distributed_world_size,
  File "/export/liujunpeng/anaconda3/envs/multivie/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/export/liujunpeng/anaconda3/envs/multivie/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/export/liujunpeng/anaconda3/envs/multivie/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/export/liujunpeng/anaconda3/envs/multivie/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/export/liujunpeng/code/Multi-View-Seq2Seq/fairseq_multi_view/fairseq_cli/train.py", line 401, in distributed_main
    main(args, init_distributed=True)
  File "/export/liujunpeng/code/Multi-View-Seq2Seq/fairseq_multi_view/fairseq_cli/train.py", line 135, in main
    s1 = source.readlines()
  File "/export/liujunpeng/anaconda3/envs/multivie/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in **position 35**: ordinal not in range(128)

**I checked the eval-set file "../data/val_sent_trans_cons_label.source", which looks like as below:** 

![image](https://user-images.githubusercontent.com/43842380/104688987-b918da00-573c-11eb-9bd1-56dee46bc9b6.png)

**that is "[34m~ " at the position 35, could help me with this? Thanks!**

**Comment by jiaaoc** [comment]
That's probably due to the encoding issues. The safest choice is to encode the text with utf-8.
